default: &default
  adapter: mysql2

  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

  pool: 50
  username: root
  password: ""
  host: localhost
  database: khmer_writing

development:
  <<: *default
  database: khmer_writing_development

test:
  <<: *default
  database: khmer_writing_test

production:
  <<: *default
